export const MEDICAL_SPECIALTIES = [
  "Allergy and immunology",
  "Anaesthesiology",
  "Cardiology",
  "Cardiothoracic surgery",
  "Critical care medicine",
  "Dermatology",
  "Ear, nose, and throat",
  "Emergency medicine",
  "Endocrinology and metabolic disorders",
  "Gastroenterology and hepatology",
  "General surgery",
  "Genetics",
  "Geriatric medicine",
  "Haematology",
  "Health maintenance",
  "Hospital medicine",
  "Infectious diseases",
  "Internal medicine",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Nutrition",
  "Obstetrics and gynaecology",
  "Oncology",
  "Ophthalmology",
  "Orthopaedics",
  "Paediatrics and adolescent medicine",
  "Palliative care",
  "Primary care",
  "Psychiatry",
  "Respiratory disorders",
  "Rheumatology",
  "Sleep medicine",
  "Surgery",
  "Urology",
  "Vascular surgery",
  "Women's health",
] as const;

export type MedicalSpecialty = (typeof MEDICAL_SPECIALTIES)[number];

export type SpecialtyTopic = {
  id: string;
  title: string;
  specialty: MedicalSpecialty;
};

function topicId(specialty: string, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  const prefix = specialty
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  return `${prefix}-${slug}`;
}

function topicsFor(
  specialty: MedicalSpecialty,
  titles: string[]
): SpecialtyTopic[] {
  return titles.map((title) => ({
    id: topicId(specialty, title),
    title,
    specialty,
  }));
}

const ALLERGY_AND_IMMUNOLOGY_TOPICS = [
  "Acute asthma exacerbation in adults",
  "Acute rhinosinusitis",
  "Adult-onset Still's disease",
  "Allergic bronchopulmonary aspergillosis",
  "Allergic rhinitis",
  "Anaphylaxis",
  "Assessment of eosinophilia",
  "Assessment of food allergies and sensitivities",
  "Assessment of urticaria",
  "Asthma in adults",
  "Asthma in children",
  "Chronic granulomatous disease",
  "Common cutaneous drug reactions",
  "Complement deficiencies",
  "Contact dermatitis",
  "Cryoglobulinaemia",
  "Dermatitis herpetiformis",
  "Eczema",
  "Eosinophilic oesophagitis",
  "Food allergy",
  "Graft-versus-host disease",
  "Hypersensitivity pneumonitis",
  "Hypogammaglobulinaemia",
  "Insect bites and stings",
  "Mast cell activation syndrome",
  "Nasal polyps",
  "Non-allergic rhinitis",
  "Occupational asthma",
  "Paediatric acute-onset neuropsychiatric syndrome",
  "Paradoxical vocal fold motion (intermittent laryngeal obstruction)",
  "Rh incompatibility",
  "Severe combined immunodeficiency",
  "Urticaria and angio-oedema",
  "Wiskott-Aldrich syndrome",
] as const;

const ANAESTHESIOLOGY_TOPICS = [
  "Abdominal aortic aneurysm",
  "Abdominal compartment syndrome",
  "Accidental hypothermia",
  "Acute aspiration",
  "Acute asthma exacerbation in adults",
  "Acute heart failure",
  "Acute kidney injury",
  "Acute liver failure",
  "Acute pancreatitis",
  "Acute respiratory distress syndrome (ARDS)",
  "Acute respiratory failure",
  "Alcohol withdrawal",
  "Amfetamine overdose",
  "Anaphylaxis",
  "Aortic dissection",
  "Aspiration pneumonia",
  "Assessment of chest pain",
  "Assessment of cyanosis in the newborn",
  "Assessment of dyspnoea",
  "Assessment of hypercalcaemia",
  "Assessment of hyperkalaemia",
  "Assessment of hypernatraemia",
  "Assessment of hypocalcaemia",
  "Assessment of hypokalaemia",
  "Assessment of metabolic acidosis",
  "Assessment of metabolic alkalosis",
  "Assessment of nausea and vomiting, adults",
  "Assessment of respiratory acidosis",
  "Assessment of respiratory alkalosis",
  "Assessment of shock",
  "Assessment of traumatic brain injury, acute",
  "Atrial flutter",
  "Atrioventricular block",
  "Atypical pneumonia",
  "Bacterial meningitis in adults",
  "Benzodiazepine overdose",
  "Botulism",
  "Bradycardia",
  "Carbon monoxide poisoning",
  "Cardiac arrest",
  "Cardiac tamponade",
  "Central airway obstruction",
  "Chronic pain syndromes",
  "Chronic pelvic pain in women",
  "Cocaine toxicity",
  "Common toxic plant ingestions",
  "Complex regional pain syndrome",
  "Cutaneous burns",
  "Deep vein thrombosis",
  "Diabetic ketoacidosis",
  "Digoxin toxicity",
  "Discogenic low back pain",
  "Disseminated intravascular coagulation",
  "Drowning",
  "Dysbarism",
  "Electrical injury",
  "Encephalitis",
  "Epiglottitis",
  "Febrile neutropenia",
  "Foreign body aspiration",
  "Fungal meningitis",
  "Heart failure with preserved ejection fraction",
  "Heat stroke in adults",
  "Heparin-induced thrombocytopenia",
  "Hepatic encephalopathy",
  "Hepatorenal syndrome",
  "Herpes zoster infection",
  "Hospital-acquired pneumonia (non COVID-19)",
  "Hypercalcaemia of malignancy",
  "Hyperosmolar hyperglycaemic state",
  "Hypertensive emergencies",
  "Ileus",
  "Inhalation injury",
  "Ischaemic stroke",
  "Lead toxicity",
  "Malignant hyperthermia",
  "Mild traumatic brain injury",
  "Musculoskeletal lower back pain",
  "Neuroleptic malignant syndrome",
  "New-onset atrial fibrillation",
  "Non-diabetic hypoglycaemia",
  "Non-ST-elevation myocardial infarction",
  "Opioid overdose",
  "Organising pneumonia",
  "Organophosphate poisoning",
  "Overview of acid-base and electrolyte disorders",
  "Overview of dysrhythmias (cardiac)",
  "Overview of meningitis",
  "Overview of stroke",
  "Overview of substance use disorders and overdose",
  "Paracetamol overdose in adults",
  "Perioperative cardiovascular risk assessment and management for non-cardiac surgery",
  "Phaeochromocytoma",
  "Pneumocystis jirovecii pneumonia",
  "Pulmonary embolism",
  "Rhabdomyolysis",
  "Salicylate poisoning",
  "Sepsis in adults",
  "Sepsis in children",
  "Serotonin syndrome",
  "ST-elevation myocardial infarction",
  "Status epilepticus",
  "Stevens-Johnson syndrome and toxic epidermal necrolysis",
  "Subarachnoid haemorrhage",
  "Sustained ventricular tachycardias",
  "Syndrome of inappropriate antidiuretic hormone",
  "Toxic ingestions in children",
  "Toxic shock syndrome",
  "Transfusion reaction",
  "Tricyclic antidepressant overdose",
  "Unstable angina",
  "Volume depletion in adults",
  "Volume depletion in children",
] as const;

const CARDIOLOGY_TOPICS = [
  "Abdominal aortic aneurysm",
  "Acute heart failure",
  "Aortic coarctation",
  "Aortic dissection",
  "Aortic regurgitation",
  "Aortic stenosis",
  "Assessment of cardiomyopathy",
  "Assessment of chest pain",
  "Assessment of clubbing",
  "Assessment of cyanosis in the newborn",
  "Assessment of dizziness",
  "Assessment of hypertension",
  "Assessment of hypotension",
  "Assessment of mediastinal mass",
  "Assessment of palpitations",
  "Assessment of pericardial effusion",
  "Assessment of peripheral oedema",
  "Assessment of shock",
  "Assessment of syncope",
  "Assessment of tachycardia",
  "Atrial flutter",
  "Atrial myxoma",
  "Atrioventricular block",
  "Bradycardia",
  "Brugada syndrome",
  "Cardiac arrest",
  "Cardiac tamponade",
  "Carotid artery stenosis",
  "Chronic coronary disease",
  "Chronic venous insufficiency",
  "Congenital heart disease",
  "Diabetic cardiovascular disease",
  "Digoxin toxicity",
  "Essential hypertension",
  "Established atrial fibrillation",
  "Focal atrial tachycardia",
  "Gestational hypertension",
  "Heart failure with preserved ejection fraction",
  "Heart failure with reduced ejection fraction",
  "Heparin-induced thrombocytopenia",
  "Hypercholesterolaemia",
  "Hypertensive emergencies",
  "Hypertriglyceridaemia",
  "Hypertrophic cardiomyopathy",
  "Idiopathic pulmonary arterial hypertension",
  "Infective endocarditis",
  "Interatrial communications (atrial septal defects)",
  "Kawasaki disease",
  "Long QT syndrome",
  "Marfan syndrome",
  "Mitral regurgitation",
  "Mitral stenosis",
  "Myocarditis",
  "Neurally mediated reflex syncope",
  "New-onset atrial fibrillation",
  "Non-ST-elevation myocardial infarction",
  "Non-sustained ventricular tachycardias",
  "Orthostatic hypotension",
  "Overview of acute coronary syndrome",
  "Overview of dysrhythmias (cardiac)",
  "Patent ductus arteriosus",
  "Patent foramen ovale",
  "Pericarditis",
  "Perioperative cardiovascular risk assessment and management for non-cardiac surgery",
  "Peripheral arterial disease",
  "Postural orthostatic tachycardia syndrome",
  "Pulmonary regurgitation",
  "Pulmonary stenosis",
  "Raynaud's phenomenon",
  "Renal artery stenosis",
  "Rheumatic fever",
  "Shock",
  "ST-elevation myocardial infarction",
  "Superior vena cava syndrome",
  "Sustained ventricular tachycardias",
  "Takayasu's arteritis",
  "Tetralogy of Fallot",
  "Tricuspid regurgitation",
  "Tricuspid stenosis",
  "Unstable angina",
  "Ventricular septal defects",
  "Wolff-Parkinson-White syndrome",
] as const;

const CARDIOTHORACIC_SURGERY_TOPICS = [
  "Abdominal aortic aneurysm",
  "Achalasia",
  "Aortic coarctation",
  "Aortic dissection",
  "Aortic regurgitation",
  "Aortic stenosis",
  "Assessment of cyanosis in the newborn",
  "Assessment of pericardial effusion",
  "Atrial myxoma",
  "Cardiac tamponade",
  "Carotid artery stenosis",
  "Congenital heart disease",
  "Hyperhidrosis",
  "Hypertrophic cardiomyopathy",
  "Infective endocarditis",
  "Interatrial communications (atrial septal defects)",
  "Marfan syndrome",
  "Mitral regurgitation",
  "Mitral stenosis",
  "Mitral valve prolapse",
  "Myocarditis",
  "Non-small cell lung cancer",
  "Oesophageal atresia and tracheo-oesophageal fistula",
  "Overview of acute coronary syndrome",
  "Patent ductus arteriosus",
  "Patent foramen ovale",
  "Pleural effusion",
  "Pneumothorax",
  "Pulmonary regurgitation",
  "Pulmonary stenosis",
  "Superior vena cava syndrome",
  "Tetralogy of Fallot",
  "Thoracic outlet syndrome",
  "Thymic tumour",
  "Tricuspid regurgitation",
  "Tricuspid stenosis",
  "Ventricular septal defects",
] as const;

const CRITICAL_CARE_MEDICINE_TOPICS = [
  "Abdominal aortic aneurysm",
  "Abdominal compartment syndrome",
  "Abusive head trauma in infants and young children",
  "Accidental hypothermia",
  "Acute aspiration",
  "Acute asthma exacerbation in adults",
  "Acute asthma exacerbation in children",
  "Acute bronchitis",
  "Acute cervical spine trauma in adults",
  "Acute cholangitis",
  "Acute cholecystitis",
  "Acute exacerbation of chronic obstructive pulmonary disease",
  "Acute heart failure",
  "Acute kidney injury",
  "Acute liver failure",
  "Acute pancreatitis",
  "Acute pyelonephritis",
  "Acute respiratory distress syndrome (ARDS)",
  "Acute respiratory failure",
  "Acute tubular necrosis",
  "Alcohol withdrawal",
  "Amfetamine overdose",
  "Anaphylaxis",
  "Animal bites",
  "Anthrax",
  "Aortic dissection",
  "Aspiration pneumonia",
  "Assessment of abdominal pain in children",
  "Assessment of abdominal pain in pregnancy",
  "Assessment of abdominal trauma in adults",
  "Assessment of acute abdomen",
  "Assessment of acute diarrhoea",
  "Assessment of acute headache in adults",
  "Assessment of acute headache in children",
  "Assessment of acute motor deficit",
  "Assessment of altered mental status",
  "Assessment of cardiomyopathy",
  "Assessment of chest pain",
  "Assessment of coma",
  "Assessment of cyanosis in the newborn",
  "Assessment of delirium",
  "Assessment of dizziness",
  "Assessment of elevated creatinine",
  "Assessment of haemoptysis",
  "Assessment of hypercalcaemia",
  "Assessment of hyperkalaemia",
  "Assessment of hypernatraemia",
  "Assessment of hypokalaemia",
  "Assessment of hyponatraemia",
  "Assessment of hypotension",
  "Assessment of liver dysfunction",
  "Assessment of lower gastrointestinal bleeding",
  "Assessment of metabolic acidosis",
  "Assessment of metabolic alkalosis",
  "Assessment of nausea and vomiting in children",
  "Assessment of nausea and vomiting, adults",
  "Assessment of pericardial effusion",
  "Assessment of psychosis",
  "Assessment of respiratory acidosis",
  "Assessment of respiratory alkalosis",
  "Assessment of shock",
  "Assessment of tachycardia",
  "Assessment of traumatic brain injury, acute",
  "Assessment of upper gastrointestinal bleeding",
  "Atrial flutter",
  "Atrioventricular block",
  "Atypical pneumonia",
  "Avian influenza A (H5N1) virus infection",
  "Avian influenza A(H7N9) virus infection",
  "Bacterial meningitis in adults",
  "Bacterial meningitis in children",
  "Benzodiazepine overdose",
  "Botulism",
  "Brachial plexus injury",
  "Bradycardia",
  "Brain abscess",
  "Carbon monoxide poisoning",
  "Cardiac arrest",
  "Cardiac tamponade",
  "Carotid artery stenosis",
  "Cauda equina syndrome",
  "Cavernous sinus thrombosis",
  "Cellulitis and erysipelas",
  "Central airway obstruction",
  "Child abuse",
  "Cholera",
  "Clostridioides difficile-associated disease",
  "Cocaine toxicity",
  "Common cutaneous drug reactions",
  "Common toxic plant ingestions",
  "Compartment syndrome of extremities",
  "Coronavirus disease 2019 (COVID-19)",
  "Croup",
  "Cutaneous burns",
  "Deep vein thrombosis",
  "Diabetic ketoacidosis",
  "Digoxin toxicity",
  "Disseminated intravascular coagulation",
  "Drowning",
  "Dysbarism",
  "Ebola disease",
  "Electrical injury",
  "Encephalitis",
  "Enterovirus D68",
  "Epiglottitis",
  "Eye trauma",
  "Febrile neutropenia",
  "Focal atrial tachycardia",
  "Food poisoning",
  "Foodborne E coli infection",
  "Foreign body aspiration",
  "Foreign body ingestion",
  "Frostbite",
  "Fungal meningitis",
  "Gangrene",
  "Generalised seizures in adults",
  "Guillain-Barre syndrome",
  "Hantavirus cardiopulmonary syndrome",
  "Heat stroke in adults",
  "Heparin-induced thrombocytopenia",
  "Hepatic encephalopathy",
  "Hepatorenal syndrome",
  "High altitude illness",
  "Hospital-acquired pneumonia (non COVID-19)",
  "Hypercalcaemia of malignancy",
  "Hypernatraemia",
  "Hyperosmolar hyperglycaemic state",
  "Hypertensive emergencies",
  "Hyponatraemia",
  "Hypoventilation syndromes",
  "Idiopathic pulmonary arterial hypertension",
  "Ileus",
  "Influenza infection",
  "Inhalation injury",
  "Inpatient glycaemic management",
  "Intra-abdominal abscess",
  "Intussusception",
  "Ischaemic bowel disease",
  "Ischaemic stroke",
  "Large bowel obstruction",
  "Lead toxicity",
  "Legionella infection",
  "Long QT syndrome",
  "Malignant hyperthermia",
  "Malignant spinal cord compression",
  "Mallory-Weiss tear",
  "Meconium aspiration syndrome",
  "Meningococcal disease",
  "Middle East respiratory syndrome (MERS)",
  "Mild traumatic brain injury",
  "Myocarditis",
  "Necrotising fasciitis",
  "Neonatal jaundice",
  "Neuroleptic malignant syndrome",
  "New-onset atrial fibrillation",
  "Non-ST-elevation myocardial infarction",
  "Opioid overdose",
  "Orbital fractures",
  "Organophosphate poisoning",
  "Overview of acid-base and electrolyte disorders",
  "Overview of acute coronary syndrome",
  "Overview of chronic alcohol use",
  "Overview of chronic obstructive pulmonary disease (COPD)",
  "Overview of dysrhythmias (cardiac)",
  "Overview of meningitis",
  "Overview of pneumonia",
  "Overview of pregnancy complications",
  "Overview of seizure disorder",
  "Overview of stroke",
  "Overview of substance use disorders and overdose",
  "Paracetamol overdose in adults",
  "Peri-orbital and orbital cellulitis",
  "Placenta praevia",
  "Placental abruption",
  "Pleural effusion",
  "Pneumocystis jirovecii pneumonia",
  "Pneumothorax",
  "Pre-eclampsia",
  "Premature newborn care",
  "Pressure ulcer",
  "Pulmonary embolism",
  "Rabies",
  "Respiratory syncytial virus infection",
  "Retropharyngeal abscess",
  "Reye's syndrome",
  "Rh incompatibility",
  "Rhabdomyolysis",
  "Rib fractures",
  "Salicylate poisoning",
  "Sepsis in adults",
  "Sepsis in children",
  "Septic arthritis",
  "Serotonin syndrome",
  "Severe acute respiratory syndrome (SARS)",
  "Shigella infection",
  "Shock",
  "Skull fractures",
  "Small bowel obstruction",
  "Spinal epidural abscess",
  "Spontaneous bacterial peritonitis",
  "ST-elevation myocardial infarction",
  "Status epilepticus",
  "Stevens-Johnson syndrome and toxic epidermal necrolysis",
  "Stroke due to spontaneous intracerebral haemorrhage",
  "Subarachnoid haemorrhage",
  "Subdural haematoma",
  "Sudden infant death syndrome",
  "Sustained ventricular tachycardias",
  "Tetanus",
  "Thoracolumbar spine trauma",
  "Toxic colitis and toxic megacolon",
  "Toxic ingestions in children",
  "Toxic shock syndrome",
  "Transfusion reaction",
  "Transverse myelitis",
  "Tricyclic antidepressant overdose",
  "Unstable angina",
  "Venous thromboembolism (VTE) prophylaxis",
  "Viral gastroenteritis in children",
  "Volume depletion in adults",
  "Volume depletion in children",
  "Wernicke's encephalopathy",
] as const;

const DERMATOLOGY_TOPICS = [
  "Acanthosis nigricans",
  "Acne vulgaris",
  "Actinic keratosis",
  "Acute varicella-zoster",
  "Alopecia areata",
  "Androgenetic alopecia",
  "Angular cheilitis",
  "Anthrax",
  "Assessment of dermatological disorders in HIV",
  "Assessment of hirsutism",
  "Assessment of maculopapular rash",
  "Assessment of oral ulceration",
  "Assessment of pruritus",
  "Assessment of pustular rash",
  "Assessment of rash in children",
  "Assessment of urticaria",
  "Assessment of vesicular-bullous rash",
  "Balanoposthitis",
  "Basal cell carcinoma",
  "Bed bugs",
  "Blastomycosis",
  "Bullous pemphigoid",
  "Common cutaneous drug reactions",
  "Common warts",
  "Contact dermatitis",
  "Cutaneous burns",
  "Cutaneous larva migrans",
  "Cutaneous T-cell lymphoma",
  "Dermatitis herpetiformis",
  "Dermatomyositis",
  "Dermatophyte infections",
  "Diabetes-related foot disease",
  "Discoid lupus erythematosus",
  "Dyshidrotic dermatitis",
  "Eczema",
  "Epidermolysis bullosa",
  "Erythema multiforme",
  "Erythema nodosum",
  "Fissured, hairy, and geographic tongue",
  "Folliculitis",
  "Genital warts",
  "Granuloma annulare",
  "Hand-foot-and-mouth disease",
  "Herpes simplex virus infection",
  "Herpes zoster infection",
  "Hidradenitis suppurativa",
  "Hyperhidrosis",
  "Ichthyosis",
  "IgA vasculitis (Henoch-Schonlein purpura)",
  "Impetigo",
  "Kaposi's sarcoma",
  "Keloid",
  "Langerhans cell histiocytosis",
  "Leishmaniasis",
  "Leprosy",
  "Lichen planus",
  "Lichen sclerosus",
  "Lichen simplex chronicus",
  "Lipoma",
  "Lyme disease",
  "Lymphogranuloma venereum",
  "Measles infection",
  "Melanoma",
  "Melasma",
  "Merkel cell carcinoma",
  "Miliaria",
  "Molluscum contagiosum",
  "Nappy rash",
  "Nevi",
  "Oral candidiasis",
  "Overview of dermatitis",
  "Overview of skin cancer",
  "Paronychia",
  "Pediculosis capitis",
  "Pemphigus",
  "Pityriasis lichenoides",
  "Pityriasis rosea",
  "Pityriasis versicolor",
  "Polyarteritis nodosa",
  "Polymorphous light eruption",
  "Porphyria cutanea tarda",
  "Psoriasis",
  "Psoriatic arthritis",
  "Recurrent aphthous stomatitis (episodic mouth ulcers)",
  "Rocky Mountain spotted fever",
  "Rosacea",
  "Roseola",
  "Rubella",
  "Scabies",
  "Seborrhoeic dermatitis",
  "Seborrhoeic keratosis",
  "Sporotrichosis",
  "Squamous cell carcinoma of the skin",
  "Stevens-Johnson syndrome and toxic epidermal necrolysis",
  "Sunburn",
  "Systemic sclerosis (scleroderma)",
  "Systemic vasculitis",
  "Tuberous sclerosis complex",
  "Type 1 neurofibromatosis",
  "Urticaria and angio-oedema",
  "Vitamin B3 deficiency",
  "Vitiligo",
  "Wrinkles",
  "Xeroderma pigmentosum",
  "Zinc deficiency",
] as const;

const ENT_TOPICS = [
  "Acquired torticollis",
  "Actinomycosis",
  "Acute otitis media",
  "Acute pharyngitis",
  "Acute rhinosinusitis",
  "Allergic rhinitis",
  "Assessment of acute headache in children",
  "Assessment of ataxia",
  "Assessment of balance disorders",
  "Assessment of chronic cough",
  "Assessment of dizziness",
  "Assessment of haemoptysis",
  "Assessment of hearing loss",
  "Assessment of hoarseness and dysphonia",
  "Assessment of olfactory loss",
  "Assessment of oral ulceration",
  "Assessment of taste disorders",
  "Assessment of thyroid mass",
  "Benign paroxysmal positional vertigo",
  "Bruxism",
  "Cavernous sinus thrombosis",
  "Cerumen impaction",
  "Cholesteatoma",
  "Chronic rhinosinusitis without nasal polyps",
  "Cleft lip and palate",
  "Common cold",
  "Congenital torticollis",
  "Dyssomnias in children",
  "Epiglottitis",
  "Epistaxis",
  "Eustachian tube dysfunction",
  "Fissured, hairy, and geographic tongue",
  "Foreign body aspiration",
  "Gingivitis",
  "Halitosis (oral malodour)",
  "Hiccups",
  "Hypoparathyroidism",
  "Labyrinthitis and vestibular neuritis",
  "Laryngeal cancer",
  "Laryngitis",
  "Laryngomalacia",
  "Meniere's disease",
  "Motion sickness",
  "Mucormycosis",
  "Mumps",
  "Nasal polyps",
  "Non-allergic rhinitis",
  "Obstructive sleep apnoea in adults",
  "Oral candidiasis",
  "Oral leukoplakia",
  "Oral mucositis",
  "Orbital fractures",
  "Oropharyngeal cancer",
  "Otitis externa",
  "Otitis media with effusion",
  "Overview of vertigo",
  "Paradoxical vocal fold motion (intermittent laryngeal obstruction)",
  "Peri-orbital and orbital cellulitis",
  "Primary hyperparathyroidism",
  "Ramsay Hunt syndrome",
  "Recurrent aphthous stomatitis (episodic mouth ulcers)",
  "Retropharyngeal abscess",
  "Scarlet fever",
  "Sialadenitis",
  "Skull fractures",
  "Snoring",
  "Temporomandibular disorders",
  "Tinnitus",
  "Tonsillitis",
  "Upper airway cough syndrome",
  "Vestibular schwannoma",
] as const;

const EMERGENCY_MEDICINE_TOPICS = [
  "Abdominal aortic aneurysm",
  "Abdominal compartment syndrome",
  "Abusive head trauma in infants and young children",
  "Accidental hypothermia",
  "Acute appendicitis",
  "Acute aspiration",
  "Acute asthma exacerbation in adults",
  "Acute asthma exacerbation in children",
  "Acute bronchitis",
  "Acute cervical spine trauma in adults",
  "Acute cholangitis",
  "Acute cholecystitis",
  "Acute conjunctivitis",
  "Acute cystitis",
  "Acute exacerbation of chronic obstructive pulmonary disease",
  "Acute heart failure",
  "Acute intermittent porphyria",
  "Acute kidney injury",
  "Acute liver failure",
  "Acute pancreatitis",
  "Acute pharyngitis",
  "Acute pyelonephritis",
  "Acute respiratory distress syndrome (ARDS)",
  "Acute respiratory failure",
  "Alcohol use disorder",
  "Alcohol withdrawal",
  "Amfetamine and methamphetamine use disorder",
  "Amfetamine overdose",
  "Anaphylaxis",
  "Animal bites",
  "Anthrax",
  "Aortic dissection",
  "Aspiration pneumonia",
  "Assessment of abdominal pain in children",
  "Assessment of abdominal pain in pregnancy",
  "Assessment of abdominal trauma in adults",
  "Assessment of acute abdomen",
  "Assessment of acute diarrhoea",
  "Assessment of acute headache in adults",
  "Assessment of acute headache in children",
  "Assessment of acute motor deficit",
  "Assessment of altered mental status",
  "Assessment of cardiomyopathy",
  "Assessment of chest pain",
  "Assessment of coma",
  "Assessment of delirium",
  "Assessment of dizziness",
  "Assessment of elevated creatinine",
  "Assessment of haemoptysis",
  "Assessment of hypercalcaemia",
  "Assessment of hyperkalaemia",
  "Assessment of hypernatraemia",
  "Assessment of hypokalaemia",
  "Assessment of hyponatraemia",
  "Assessment of hypotension",
  "Assessment of lower gastrointestinal bleeding",
  "Assessment of metabolic acidosis",
  "Assessment of metabolic alkalosis",
  "Assessment of nausea and vomiting in children",
  "Assessment of nausea and vomiting, adults",
  "Assessment of palpitations",
  "Assessment of pericardial effusion",
  "Assessment of psychosis",
  "Assessment of respiratory acidosis",
  "Assessment of respiratory alkalosis",
  "Assessment of shock",
  "Assessment of syncope",
  "Assessment of tachycardia",
  "Assessment of traumatic brain injury, acute",
  "Assessment of upper gastrointestinal bleeding",
  "Atrial flutter",
  "Atrioventricular block",
  "Atypical pneumonia",
  "Avian influenza A (H5N1) virus infection",
  "Avian influenza A(H7N9) virus infection",
  "Bacterial meningitis in adults",
  "Benzodiazepine overdose",
  "Botulism",
  "Brachial plexus injury",
  "Bradycardia",
  "Brain abscess",
  "Carbon monoxide poisoning",
  "Cardiac arrest",
  "Cardiac tamponade",
  "Cauda equina syndrome",
  "Cavernous sinus thrombosis",
  "Cellulitis and erysipelas",
  "Central airway obstruction",
  "Child abuse",
  "Chlamydia pneumoniae infection",
  "Cholelithiasis (gallstones)",
  "Cholera",
  "Clavicle fracture",
  "Cocaine toxicity",
  "Common cold",
  "Common cutaneous drug reactions",
  "Common toxic plant ingestions",
  "Community-acquired pneumonia in children",
  "Compartment syndrome of extremities",
  "Corneal abrasions",
  "Croup",
  "Cutaneous burns",
  "Deep vein thrombosis",
  "Dental abscess",
  "Diabetic hypoglycaemia",
  "Diabetic ketoacidosis",
  "Digoxin toxicity",
  "Disseminated intravascular coagulation",
  "Drowning",
  "Dysbarism",
  "Ebola disease",
  "Ectopic pregnancy",
  "Electrical injury",
  "Encephalitis",
  "Enterovirus D68",
  "Epiglottitis",
  "Epistaxis",
  "Eye trauma",
  "Febrile seizure",
  "Focal atrial tachycardia",
  "Food poisoning",
  "Foodborne E coli infection",
  "Foreign body aspiration",
  "Foreign body ingestion",
  "Frailty",
  "Frostbite",
  "Gangrene",
  "Generalised seizures in adults",
  "Generalised seizures in children",
  "Groin pain",
  "Hantavirus cardiopulmonary syndrome",
  "Heat stroke in adults",
  "Hepatorenal syndrome",
  "High altitude illness",
  "Hyperkalaemia in adults",
  "Hypernatraemia",
  "Hyperosmolar hyperglycaemic state",
  "Hypertensive emergencies",
  "Hyponatraemia",
  "Ileus",
  "Influenza infection",
  "Inhalation injury",
  "Insect bites and stings",
  "Intra-abdominal abscess",
  "Intussusception",
  "Ischaemic bowel disease",
  "Ischaemic stroke",
  "Joint dislocation",
  "Keratitis",
  "Large bowel obstruction",
  "Lead toxicity",
  "Legionella infection",
  "Long bone fracture",
  "Long QT syndrome",
  "Malignant hyperthermia",
  "Malignant spinal cord compression",
  "Mallory-Weiss tear",
  "Marine toxins (saxitoxin, tetrodotoxin, conotoxin)",
  "Mast cell activation syndrome",
  "Mastitis and breast abscess",
  "Medial collateral ligament injury",
  "Meningococcal disease",
  "Meniscal tear",
  "Mental health response to disasters and other critical incidents",
  "Middle East respiratory syndrome (MERS)",
  "Mild traumatic brain injury",
  "Musculoskeletal sprains and strains",
  "Myocarditis",
  "Necrotising fasciitis",
  "Nephrolithiasis",
  "Neuroleptic malignant syndrome",
  "New-onset atrial fibrillation",
  "Non-ST-elevation myocardial infarction",
  "Opioid overdose",
  "Orbital fractures",
  "Organophosphate poisoning",
  "Osteomyelitis",
  "Ovarian torsion",
  "Overview of acid-base and electrolyte disorders",
  "Overview of acute coronary syndrome",
  "Overview of chronic alcohol use",
  "Overview of chronic obstructive pulmonary disease (COPD)",
  "Overview of dysrhythmias (cardiac)",
  "Overview of meningitis",
  "Overview of musculoskeletal pain",
  "Overview of pneumonia",
  "Overview of pregnancy complications",
  "Overview of seizure disorder",
  "Overview of stroke",
  "Overview of substance use disorders and overdose",
  "Paracetamol overdose in adults",
  "Pelvic inflammatory disease",
  "Peri-orbital and orbital cellulitis",
  "Pericarditis",
  "Phaeochromocytoma",
  "Placenta praevia",
  "Placental abruption",
  "Pleural effusion",
  "Pneumocystis jirovecii pneumonia",
  "Pneumothorax",
  "Post-exposure HIV prophylaxis",
  "Postpartum haemorrhage",
  "Pre-eclampsia",
  "Premature labour",
  "Pulmonary embolism",
  "Pyloric stenosis",
  "Rabies",
  "Respiratory syncytial virus infection",
  "Retropharyngeal abscess",
  "Reye's syndrome",
  "Rh incompatibility",
  "Rhabdomyolysis",
  "Rib fractures",
  "Salicylate poisoning",
  "Sepsis in adults",
  "Sepsis in children",
  "Septic arthritis",
  "Serotonin syndrome",
  "Severe acute respiratory syndrome (SARS)",
  "Sexual abuse and assault",
  "Shigella infection",
  "Shock",
  "Skull fractures",
  "Small bowel obstruction",
  "Spinal epidural abscess",
  "Spontaneous bacterial peritonitis",
  "ST-elevation myocardial infarction",
  "Status epilepticus",
  "Stevens-Johnson syndrome and toxic epidermal necrolysis",
  "Stroke due to spontaneous intracerebral haemorrhage",
  "Subarachnoid haemorrhage",
  "Subdural haematoma",
  "Sudden infant death syndrome",
  "Suicide risk mitigation",
  "Sunburn",
  "Superficial vein thrombosis",
  "Sustained ventricular tachycardias",
  "Testicular torsion",
  "Tetanus",
  "Thoracolumbar spine trauma",
  "Toxic colitis and toxic megacolon",
  "Toxic ingestions in children",
  "Toxic shock syndrome",
  "Transient ischaemic attack",
  "Transverse myelitis",
  "Tricyclic antidepressant overdose",
  "Unstable angina",
  "Viral gastroenteritis in adults",
  "Viral gastroenteritis in children",
  "Vitamin B1 deficiency",
  "Volume depletion in adults",
  "Volume depletion in children",
  "Wernicke's encephalopathy",
  "Wrist fractures",
] as const;

const ENDOCRINOLOGY_TOPICS = [
  "Abetalipoproteinaemia",
  "Acanthosis nigricans",
  "Acromegaly",
  "Adrenal suppression",
  "Anabolic steroid use disorder",
  "Androgenetic alopecia",
  "Arginine vasopressin deficiency or resistance (Diabetes insipidus)",
  "Assessment of cardiomyopathy",
  "Assessment of fatigue",
  "Assessment of hirsutism",
  "Assessment of hypercalcaemia",
  "Assessment of hyperkalaemia",
  "Assessment of hypernatraemia",
  "Assessment of hyperprolactinaemia",
  "Assessment of hypertension",
  "Assessment of hypocalcaemia",
  "Assessment of hypokalaemia",
  "Assessment of hyponatraemia",
  "Assessment of incidental adrenal mass",
  "Assessment of magnesium deficiency",
  "Assessment of metabolic alkalosis",
  "Assessment of pituitary mass",
  "Assessment of primary amenorrhoea",
  "Assessment of secondary amenorrhoea",
  "Assessment of short stature",
  "Assessment of thyroid mass",
  "Assessment of unintentional weight loss",
  "Bariatric surgery sequelae",
  "Carcinoid syndrome",
  "Central hypothyroidism",
  "Congenital adrenal hyperplasia",
  "Cushing syndrome",
  "Delayed puberty",
  "Diabetes-related foot disease",
  "Diabetic cardiovascular disease",
  "Diabetic hypoglycaemia",
  "Diabetic ketoacidosis",
  "Diabetic kidney disease",
  "Diabetic neuropathy",
  "Diabetic retinopathy",
  "DiGeorge syndrome",
  "Gastroparesis",
  "Gestational diabetes mellitus",
  "Graves' disease",
  "Growth hormone deficiency in children",
  "Gynaecomastia",
  "Haemochromatosis",
  "Hypercalcaemia of malignancy",
  "Hypercholesterolaemia",
  "Hyperkalaemia in adults",
  "Hypernatraemia",
  "Hyperosmolar hyperglycaemic state",
  "Hypertriglyceridaemia",
  "Hypogonadism in men",
  "Hyponatraemia",
  "Hypoparathyroidism",
  "Hypopituitarism",
  "Infertility in women",
  "Inpatient glycaemic management",
  "Klinefelter syndrome",
  "Lesch-Nyhan disease",
  "Male factor infertility",
  "Menopause",
  "Metabolic syndrome",
  "Multiple endocrine neoplasia syndromes",
  "Non-diabetic hypoglycaemia",
  "Obesity in adults",
  "Obesity in children",
  "Osteomalacia",
  "Osteoporosis",
  "Osteoporotic spinal compression fractures",
  "Overview of acid-base and electrolyte disorders",
  "Overview of diabetes",
  "Overview of thyroid dysfunction",
  "Paget's disease of bone",
  "Painless lymphocytic thyroiditis",
  "Phaeochromocytoma",
  "Pituitary adenoma",
  "Polycystic ovary syndrome",
  "Precocious puberty",
  "Premature ovarian failure",
  "Primary adrenal insufficiency",
  "Primary aldosteronism",
  "Primary hyperparathyroidism",
  "Primary hypothyroidism",
  "Prolactinoma",
  "Pseudohypoparathyroidism",
  "Psychogenic polydipsia",
  "Rickets",
  "Secondary hyperparathyroidism",
  "Steatotic liver disease",
  "Subacute thyroiditis",
  "Syndrome of inappropriate antidiuretic hormone",
  "Thyroid cancer",
  "Thyroid function testing",
  "Toxic multinodular goitre",
  "Toxic thyroid adenoma",
  "Type 1 diabetes",
  "Type 2 diabetes in adults",
  "Type 2 diabetes in children",
  "VIPoma",
  "Vitamin D deficiency",
  "Zollinger-Ellison syndrome",
] as const;

const WOMENS_HEALTH_TOPICS = [
  "Abnormal uterine bleeding",
  "Acute cystitis",
  "Antiphospholipid syndrome",
  "Assessment of abdominal pain in pregnancy",
  "Assessment of abnormal uterine bleeding",
  "Assessment of breast mass",
  "Assessment of dysmenorrhoea",
  "Assessment of dyspareunia",
  "Assessment of dysuria",
  "Assessment of primary amenorrhoea",
  "Assessment of recurrent miscarriage",
  "Assessment of secondary amenorrhoea",
  "Assessment of vaginal bleeding",
  "Assessment of vaginal discharge",
  "Bartholin's cyst",
  "Brachial plexus birth injury",
  "Breech presentation",
  "Cervical cancer",
  "Cervical cancer screening",
  "Cervicitis",
  "Chancroid and cutaneous ulcers",
  "Chronic pelvic pain in women",
  "Contraception",
  "Ectopic pregnancy",
  "Endometrial cancer",
  "Endometriosis",
  "Fibrocystic breasts",
  "Genital tract chlamydia infection",
  "Genital warts",
  "Gestational diabetes mellitus",
  "Gestational hypertension",
  "Gonorrhoea infection",
  "HELLP syndrome",
  "Herpes simplex virus infection",
  "HIV in pregnancy",
  "Infertility in women",
  "Interstitial cystitis (bladder pain syndrome)",
  "Intrahepatic cholestasis of pregnancy",
  "Lymphogranuloma venereum",
  "Mastitis and breast abscess",
  "Meconium aspiration syndrome",
  "Melasma",
  "Menopause",
  "Miscarriage",
  "Molar pregnancies",
  "Mycoplasma pneumoniae infection",
  "Nausea and vomiting in pregnancy",
  "Omphalocele and gastroschisis",
  "Ovarian cancer",
  "Ovarian cysts",
  "Ovarian torsion",
  "Overview of pregnancy complications",
  "Overview of sexually transmitted infections",
  "Pelvic inflammatory disease",
  "Placenta praevia",
  "Placental abruption",
  "Polycystic ovary syndrome",
  "Postnatal depression",
  "Pre-eclampsia",
  "Premature labour",
  "Premature ovarian failure",
  "Premenstrual syndrome and dysphoric disorder",
  "Rh incompatibility",
  "Routine antenatal care",
  "Sexual dysfunction in women",
  "Urethritis",
  "Urinary incontinence in women",
  "Urinary tract infections in women",
  "Uterine fibroids",
  "Uterine prolapse",
  "Vaginitis",
  "Vitamin D deficiency",
  "Zika virus infection",
] as const;

const VASCULAR_SURGERY_TOPICS = [
  "Abdominal aortic aneurysm",
  "Angiodysplasia of the colon and small intestine",
  "Aortic coarctation",
  "Aortic dissection",
  "Buerger's disease",
  "Chronic venous insufficiency",
  "Deep vein thrombosis",
  "Diabetes-related foot disease",
  "Gangrene",
  "Ischaemic bowel disease",
  "Peripheral arterial disease",
  "Pressure ulcer",
  "Pulmonary embolism",
  "Renal artery stenosis",
  "Superficial vein thrombosis",
  "Superior vena cava syndrome",
  "Thoracic outlet syndrome",
  "Varicose veins",
  "Venous thromboembolism (VTE) prophylaxis",
] as const;

const UROLOGY_TOPICS = [
  "Acute cystitis",
  "Acute epididymitis",
  "Acute kidney injury",
  "Acute prostatitis",
  "Acute pyelonephritis",
  "Anatomical penile abnormalities",
  "Assessment of dysuria",
  "Assessment of elevated creatinine",
  "Assessment of non-visible haematuria",
  "Assessment of proteinuria",
  "Assessment of visible haematuria",
  "Balanoposthitis",
  "Benign prostatic hyperplasia",
  "Bladder cancer",
  "Chancroid and cutaneous ulcers",
  "Chronic kidney disease",
  "Chronic pelvic pain in women",
  "Chronic pyelonephritis",
  "Cryptorchidism",
  "Enuresis",
  "Erectile dysfunction",
  "Genital tract chlamydia infection",
  "Genital warts",
  "Gonorrhoea infection",
  "Herpes simplex virus infection",
  "Hydrocele",
  "Hypogonadism in men",
  "Inguinal hernia in adults",
  "Interstitial cystitis (bladder pain syndrome)",
  "Klinefelter syndrome",
  "Lichen sclerosus",
  "Lymphogranuloma venereum",
  "Male factor infertility",
  "Medullary sponge kidney",
  "Mycoplasma pneumoniae infection",
  "Nephrolithiasis",
  "Obstructive uropathy",
  "Overview of sexually transmitted infections",
  "Paraphimosis",
  "Polycystic kidney disease",
  "Priapism",
  "Primary prostate pain syndrome",
  "Prostate cancer",
  "Renal cell carcinoma",
  "Testicular cancer",
  "Testicular torsion",
  "Urethritis",
  "Urinary incontinence in women",
  "Urinary tract infections in children",
  "Urinary tract infections in men",
  "Urinary tract infections in women",
  "Varicocele",
  "Wilms' tumour",
] as const;

const SURGERY_TOPICS = [
  "Abdominal aortic aneurysm",
  "Abdominal compartment syndrome",
  "Abnormal uterine bleeding",
  "Achalasia",
  "Acquired torticollis",
  "Acromegaly",
  "Actinomycosis",
  "Acute appendicitis",
  "Acute cervical spine trauma in adults",
  "Acute cholangitis",
  "Acute cholecystitis",
  "Acute conjunctivitis",
  "Acute cystitis",
  "Acute epididymitis",
  "Acute kidney injury",
  "Acute otitis media",
  "Acute pancreatitis",
  "Acute pharyngitis",
  "Acute prostatitis",
  "Acute pyelonephritis",
  "Acute rhinosinusitis",
  "Adenocarcinoma of unknown primary site",
  "Adhesive capsulitis",
  "Adolescent idiopathic scoliosis",
  "Age-related macular degeneration",
  "Allergic rhinitis",
  "Amblyopia",
  "Anabolic steroid use disorder",
  "Anal fissure",
  "Anatomical penile abnormalities",
  "Angiodysplasia of the colon and small intestine",
  "Angle-closure glaucoma",
  "Animal bites",
  "Ankle fractures",
  "Anorectal abscess",
  "Anterior cruciate ligament injury",
  "Antiphospholipid syndrome",
  "Aortic coarctation",
  "Aortic dissection",
  "Aortic regurgitation",
  "Aortic stenosis",
  "Arginine vasopressin deficiency or resistance (Diabetes insipidus)",
  "Assessment of abdominal pain in children",
  "Assessment of abdominal pain in pregnancy",
  "Assessment of abdominal trauma in adults",
  "Assessment of abnormal uterine bleeding",
  "Assessment of acute abdomen",
  "Assessment of acute headache in adults",
  "Assessment of acute headache in children",
  "Assessment of acute motor deficit",
  "Assessment of altered mental status",
  "Assessment of ataxia",
  "Assessment of back pain",
  "Assessment of balance disorders",
  "Assessment of breast mass",
  "Assessment of chronic abdominal pain",
  "Assessment of chronic cough",
  "Assessment of coma",
  "Assessment of cranial nerve mononeuropathy",
  "Assessment of cyanosis in the newborn",
  "Assessment of dizziness",
  "Assessment of dysmenorrhoea",
  "Assessment of dyspareunia",
  "Assessment of dysuria",
  "Assessment of elevated creatinine",
  "Assessment of gait disorders in children",
  "Assessment of haemoptysis",
  "Assessment of hearing loss",
  "Assessment of hoarseness and dysphonia",
  "Assessment of incidental adrenal mass",
  "Assessment of inflamed joint",
  "Assessment of knee injury",
  "Assessment of lower extremity mononeuropathy",
  "Assessment of lower gastrointestinal bleeding",
  "Assessment of lymphadenopathy",
  "Assessment of neck pain",
  "Assessment of non-visible haematuria",
  "Assessment of olfactory loss",
  "Assessment of oral ulceration",
  "Assessment of paraesthesias",
  "Assessment of pericardial effusion",
  "Assessment of pituitary mass",
  "Assessment of postoperative fever",
  "Assessment of primary amenorrhoea",
  "Assessment of proteinuria",
  "Assessment of ptosis",
  "Assessment of recurrent miscarriage",
  "Assessment of red eye",
  "Assessment of secondary amenorrhoea",
  "Assessment of seronegative arthritis",
  "Assessment of splenomegaly",
  "Assessment of taste disorders",
  "Assessment of thyroid mass",
  "Assessment of traumatic brain injury, acute",
  "Assessment of upper extremity mononeuropathy",
  "Assessment of upper gastrointestinal bleeding",
  "Assessment of vaginal bleeding",
  "Assessment of vaginal discharge",
  "Assessment of visible haematuria",
  "Assessment of vision loss",
  "Astigmatism",
  "Atrial myxoma",
  "Balanoposthitis",
  "Bariatric surgery sequelae",
  "Bartholin's cyst",
  "Benign paroxysmal positional vertigo",
  "Benign prostatic hyperplasia",
  "Biliary atresia",
  "Bladder cancer",
  "Blepharitis",
  "Brachial plexus birth injury",
  "Brachial plexus injury",
  "Brain abscess",
  "Breast cancer in situ",
  "Breech presentation",
  "Bruxism",
  "Buerger's disease",
  "Bursitis",
  "Carcinoid syndrome",
  "Cardiac tamponade",
  "Carpal tunnel syndrome",
  "Cataracts",
  "Cauda equina syndrome",
  "Cavernous sinus thrombosis",
  "Cellulitis and erysipelas",
  "Central hypothyroidism",
  "Cerebral aneurysm",
  "Cerebral arteriovenous malformation",
  "Cerumen impaction",
  "Cervical cancer",
  "Cervical cancer screening",
  "Cervicitis",
  "Chancroid and cutaneous ulcers",
  "Cholelithiasis (gallstones)",
  "Cholesteatoma",
  "Chronic kidney disease",
  "Chronic pelvic pain in women",
  "Chronic pyelonephritis",
  "Chronic rhinosinusitis without nasal polyps",
  "Chronic spinal cord injury",
  "Chronic venous insufficiency",
  "Clavicle fracture",
  "Cleft lip and palate",
  "Coccygodynia",
  "Colorectal cancer",
  "Common cold",
  "Compartment syndrome of extremities",
  "Congenital heart disease",
  "Congenital torticollis",
  "Contraception",
  "Corneal abrasions",
  "Craniopharyngioma",
  "Cryptorchidism",
  "Cushing syndrome",
  "Cutaneous burns",
  "Deep vein thrombosis",
  "Degenerative cervical spine disease",
  "Dental abscess",
  "Developmental dysplasia of the hip",
  "Diabetes-related foot disease",
  "Diabetic retinopathy",
  "Discogenic low back pain",
  "Diverticular disease",
  "Dry eye disease",
  "Dupuytren's contracture",
  "Dyssomnias in children",
  "Ectopic pregnancy",
  "Endometrial cancer",
  "Endometriosis",
  "Enuresis",
  "Epicondylitis",
  "Epiglottitis",
  "Epistaxis",
  "Equinovarus foot deformity",
  "Erectile dysfunction",
  "Eustachian tube dysfunction",
  "Eye trauma",
  "Fibrocystic breasts",
  "Fissured, hairy, and geographic tongue",
  "Foreign body aspiration",
  "Foreign body ingestion",
  "Frostbite",
  "Ganglion cyst",
  "Gangrene",
  "Gastroparesis",
  "Genital tract chlamydia infection",
  "Genital warts",
  "Gestational diabetes mellitus",
  "Gestational hypertension",
  "Gingivitis",
  "Gliomas",
  "Gonorrhoea infection",
  "Groin pain",
  "Haemorrhoids",
  "Halitosis (oral malodour)",
  "Hepatocellular carcinoma",
  "Herpes simplex virus infection",
  "Hiatus hernia",
  "Hiccups",
  "Hidradenitis suppurativa",
  "Hip fracture",
  "Hirschsprung's disease",
  "HIV in pregnancy",
  "Hydrocele",
  "Hyperhidrosis",
  "Hypertrophic cardiomyopathy",
  "Hypogonadism in men",
  "Hypoparathyroidism",
  "Hypopituitarism",
  "Idiopathic intracranial hypertension",
  "Ileus",
  "Iliotibial band syndrome",
  "Infective endocarditis",
  "Infertility in women",
  "Inguinal hernia in adults",
  "Inpatient glycaemic management",
  "Interatrial communications (atrial septal defects)",
  "Interstitial cystitis (bladder pain syndrome)",
  "Intestinal malrotation",
  "Intra-abdominal abscess",
  "Intussusception",
  "Ischaemic bowel disease",
  "Joint dislocation",
  "Keloid",
  "Keratitis",
  "Langerhans cell histiocytosis",
  "Large bowel obstruction",
  "Laryngeal cancer",
  "Laryngitis",
  "Laryngomalacia",
  "Legg-Calvé-Perthes' disease",
  "Lipoma",
  "Long bone fracture",
  "Lymphoedema",
  "Lymphogranuloma venereum",
  "Male factor infertility",
  "Malignant hyperthermia",
  "Malignant spinal cord compression",
  "Mallory-Weiss tear",
  "Marfan syndrome",
  "Mastitis and breast abscess",
  "Meckel's diverticulum",
  "Meconium aspiration syndrome",
  "Medial collateral ligament injury",
  "Medullary sponge kidney",
  "Medulloblastoma",
  "Melanoma",
  "Melasma",
  "Meniere's disease",
  "Meningioma",
  "Meniscal tear",
  "Menopause",
  "Mild traumatic brain injury",
  "Miscarriage",
  "Mitral regurgitation",
  "Mitral stenosis",
  "Mitral valve prolapse",
  "Molar pregnancies",
  "Motion sickness",
  "Mucormycosis",
  "Mumps",
  "Musculoskeletal lower back pain",
  "Musculoskeletal sprains and strains",
  "Mycoplasma pneumoniae infection",
  "Myocarditis",
  "Nasal polyps",
  "Nausea and vomiting in pregnancy",
  "Necrotising fasciitis",
  "Nephrolithiasis",
  "Neuroblastoma",
  "Night blindness",
  "Non-allergic rhinitis",
  "Non-small cell lung cancer",
  "Normal pressure hydrocephalus",
  "Obstructive sleep apnoea in adults",
  "Obstructive uropathy",
  "Oesophageal atresia and tracheo-oesophageal fistula",
  "Oesophageal cancer",
  "Oesophageal varices",
  "Omphalocele and gastroschisis",
  "Open-angle glaucoma",
  "Optic neuritis",
  "Oral candidiasis",
  "Oral leukoplakia",
  "Oral mucositis",
  "Orbital fractures",
  "Oropharyngeal cancer",
  "Osgood-Schlatter's disease",
  "Osteoarthritis",
  "Osteochondritis dissecans",
  "Osteomyelitis",
  "Osteoporotic spinal compression fractures",
  "Osteosarcoma",
  "Otitis externa",
  "Otitis media with effusion",
  "Ovarian cancer",
  "Ovarian cysts",
  "Ovarian torsion",
  "Overview of acute coronary syndrome",
  "Overview of brain tumours",
  "Overview of musculoskeletal pain",
  "Overview of pregnancy complications",
  "Overview of sexually transmitted infections",
  "Overview of sport-related injuries",
  "Overview of stroke",
  "Overview of vertigo",
  "Overview of work-related musculoskeletal disorders",
  "Paget's disease of bone",
  "Paradoxical vocal fold motion (intermittent laryngeal obstruction)",
  "Paraphimosis",
  "Paronychia",
  "Patellofemoral pain syndrome",
  "Patent ductus arteriosus",
  "Patent foramen ovale",
  "Pelvic inflammatory disease",
  "Peri-orbital and orbital cellulitis",
  "Perioperative cardiovascular risk assessment and management for non-cardiac surgery",
  "Peripheral arterial disease",
  "Phaeochromocytoma",
  "Pilonidal disease",
  "Pituitary adenoma",
  "Placenta praevia",
  "Placental abruption",
  "Plantar fasciitis",
  "Pleural effusion",
  "Pneumothorax",
  "Polycystic kidney disease",
  "Polycystic ovary syndrome",
  "Popliteal cyst",
  "Postnatal depression",
  "Pre-eclampsia",
  "Premature labour",
  "Premature ovarian failure",
  "Premenstrual syndrome and dysphoric disorder",
  "Pressure ulcer",
  "Priapism",
  "Primary hyperparathyroidism",
  "Primary invasive breast cancer",
  "Prolactinoma",
  "Prostate cancer",
  "Pterygium",
  "Pulmonary embolism",
  "Pulmonary regurgitation",
  "Pulmonary stenosis",
  "Pyloric stenosis",
  "Recurrent aphthous stomatitis (episodic mouth ulcers)",
  "Renal artery stenosis",
  "Renal cell carcinoma",
  "Retinal detachment",
  "Retinal vein occlusion",
  "Retinitis pigmentosa",
  "Retinoblastoma",
  "Retropharyngeal abscess",
  "Rh incompatibility",
  "Rotator cuff injury",
  "Routine antenatal care",
  "Scarlet fever",
  "Septic arthritis",
  "Sexual dysfunction in women",
  "Short bowel syndrome",
  "Sialadenitis",
  "Skull fractures",
  "Slipped capital femoral epiphysis",
  "Small bowel obstruction",
  "Snoring",
  "Soft-tissue sarcoma",
  "Spina bifida and neural tube defects",
  "Spinal epidural abscess",
  "Spinal stenosis",
  "Stomach cancer",
  "Strabismus",
  "Stroke due to spontaneous intracerebral haemorrhage",
  "Stye and chalazion",
  "Subarachnoid haemorrhage",
  "Subdural haematoma",
  "Superficial vein thrombosis",
  "Superior vena cava syndrome",
  "Syndrome of inappropriate antidiuretic hormone",
  "Temporomandibular disorders",
  "Tendinopathy",
  "Tenosynovitis of the hand and wrist",
  "Testicular cancer",
  "Testicular torsion",
  "Tetralogy of Fallot",
  "Thoracic outlet syndrome",
  "Thoracolumbar spine trauma",
  "Thymic tumour",
  "Tinnitus",
  "Tonsillitis",
  "Torsion of the lower limb in children",
  "Toxic colitis and toxic megacolon",
  "Trachoma",
  "Transient synovitis of the hip",
  "Tricuspid regurgitation",
  "Tricuspid stenosis",
  "Trigeminal neuralgia",
  "Umbilical hernia in children",
  "Upper airway cough syndrome",
  "Urethritis",
  "Urinary incontinence in women",
  "Urinary tract infections in children",
  "Urinary tract infections in men",
  "Urinary tract infections in women",
  "Uterine fibroids",
  "Uterine prolapse",
  "Uveitis",
  "Vaginitis",
  "Varicocele",
  "Varicose veins",
  "Venous thromboembolism (VTE) prophylaxis",
  "Ventricular septal defects",
  "Vestibular schwannoma",
  "Vitamin D deficiency",
  "Wilms' tumour",
  "Wrist fractures",
  "Xeroderma pigmentosum",
  "Zika virus infection",
] as const;

const SLEEP_MEDICINE_TOPICS = [
  "Assessment of fatigue",
  "Central sleep apnoea",
  "Dyssomnias in children",
  "Insomnia",
  "Jet lag and sleep phase disorders",
  "Narcolepsy",
  "Obstructive sleep apnoea in adults",
  "Parasomnias in adults",
  "Parasomnias in children",
  "Periodic limb movement disorder",
  "Restless legs syndrome",
  "Snoring",
] as const;

const RHEUMATOLOGY_TOPICS = [
  "Adhesive capsulitis",
  "Adult-onset Still's disease",
  "Assessment of fatigue",
  "Assessment of inflamed joint",
  "Assessment of seronegative arthritis",
  "Assessment of unintentional weight loss",
  "Autoimmune hepatitis",
  "Axial spondyloarthritis",
  "Behcet's syndrome",
  "Buerger's disease",
  "Bursitis",
  "Calcium pyrophosphate deposition",
  "Complex regional pain syndrome",
  "Costochondritis",
  "Cryoglobulinaemia",
  "Degenerative cervical spine disease",
  "Dermatomyositis",
  "Diffuse idiopathic skeletal hyperostosis",
  "Discogenic low back pain",
  "Discoid lupus erythematosus",
  "Dry eye disease",
  "Dupuytren's contracture",
  "Eosinophilic granulomatosis with polyangiitis (Churg-Strauss syndrome)",
  "Epicondylitis",
  "Erythema nodosum",
  "Familial Mediterranean fever",
  "Felty's syndrome",
  "Fibromyalgia",
  "Giant cell arteritis",
  "Gout",
  "Granulomatosis with polyangiitis",
  "Groin pain",
  "IgA vasculitis (Henoch-Schonlein purpura)",
  "Iliotibial band syndrome",
  "Juvenile idiopathic arthritis",
  "Kawasaki disease",
  "Limited cutaneous systemic sclerosis",
  "Lyme disease",
  "Muscle cramps",
  "Musculoskeletal lower back pain",
  "Musculoskeletal sprains and strains",
  "Myalgic encephalomyelitis (Chronic fatigue syndrome)",
  "Osgood-Schlatter's disease",
  "Osteoarthritis",
  "Osteochondritis dissecans",
  "Osteomalacia",
  "Osteoporosis",
  "Osteoporotic spinal compression fractures",
  "Overlap syndromes",
  "Overview of musculoskeletal pain",
  "Overview of work-related musculoskeletal disorders",
  "Paediatric acute-onset neuropsychiatric syndrome",
  "Paget's disease of bone",
  "Patellofemoral pain syndrome",
  "Polyarteritis nodosa",
  "Polymyalgia rheumatica",
  "Popliteal cyst",
  "Psoriatic arthritis",
  "Raynaud's phenomenon",
  "Reactive arthritis",
  "Rheumatoid arthritis",
  "Rotator cuff injury",
  "Sarcoidosis",
  "Septic arthritis",
  "Sjogren syndrome",
  "Systemic lupus erythematosus",
  "Systemic sclerosis (scleroderma)",
  "Systemic vasculitis",
  "Takayasu's arteritis",
  "Tendinopathy",
  "Tenosynovitis of the hand and wrist",
  "Transient synovitis of the hip",
] as const;

export const SPECIALTY_TOPIC_GROUPS: Array<{
  specialty: MedicalSpecialty;
  topics: SpecialtyTopic[];
}> = [
  {
    specialty: "Allergy and immunology",
    topics: topicsFor("Allergy and immunology", [
      ...ALLERGY_AND_IMMUNOLOGY_TOPICS,
    ]),
  },
  {
    specialty: "Anaesthesiology",
    topics: topicsFor("Anaesthesiology", [...ANAESTHESIOLOGY_TOPICS]),
  },
  {
    specialty: "Cardiology",
    topics: topicsFor("Cardiology", [...CARDIOLOGY_TOPICS]),
  },
  {
    specialty: "Cardiothoracic surgery",
    topics: topicsFor("Cardiothoracic surgery", [
      ...CARDIOTHORACIC_SURGERY_TOPICS,
    ]),
  },
  {
    specialty: "Critical care medicine",
    topics: topicsFor("Critical care medicine", [
      ...CRITICAL_CARE_MEDICINE_TOPICS,
    ]),
  },
  {
    specialty: "Dermatology",
    topics: topicsFor("Dermatology", [...DERMATOLOGY_TOPICS]),
  },
  {
    specialty: "Ear, nose, and throat",
    topics: topicsFor("Ear, nose, and throat", [...ENT_TOPICS]),
  },
  {
    specialty: "Emergency medicine",
    topics: topicsFor("Emergency medicine", [...EMERGENCY_MEDICINE_TOPICS]),
  },
  {
    specialty: "Endocrinology and metabolic disorders",
    topics: topicsFor("Endocrinology and metabolic disorders", [
      ...ENDOCRINOLOGY_TOPICS,
    ]),
  },
  {
    specialty: "Women's health",
    topics: topicsFor("Women's health", [...WOMENS_HEALTH_TOPICS]),
  },
  {
    specialty: "Vascular surgery",
    topics: topicsFor("Vascular surgery", [...VASCULAR_SURGERY_TOPICS]),
  },
  {
    specialty: "Urology",
    topics: topicsFor("Urology", [...UROLOGY_TOPICS]),
  },
  {
    specialty: "Surgery",
    topics: topicsFor("Surgery", [...SURGERY_TOPICS]),
  },
  {
    specialty: "Sleep medicine",
    topics: topicsFor("Sleep medicine", [...SLEEP_MEDICINE_TOPICS]),
  },
  {
    specialty: "Rheumatology",
    topics: topicsFor("Rheumatology", [...RHEUMATOLOGY_TOPICS]),
  },
];

export const ALL_SPECIALTY_TOPICS: SpecialtyTopic[] =
  SPECIALTY_TOPIC_GROUPS.flatMap((group) => group.topics);

export function filterSpecialtyTopics(query: string): SpecialtyTopic[] {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_SPECIALTY_TOPICS;
  return ALL_SPECIALTY_TOPICS.filter(
    (topic) =>
      topic.title.toLowerCase().includes(q) ||
      topic.specialty.toLowerCase().includes(q)
  );
}

export function specialtiesWithoutTopics(): MedicalSpecialty[] {
  const withTopics = new Set(
    SPECIALTY_TOPIC_GROUPS.map((group) => group.specialty)
  );
  return MEDICAL_SPECIALTIES.filter((s) => !withTopics.has(s));
}

export function specialtySlug(specialty: string): string {
  return specialty
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export function getSpecialtyBySlug(
  slug: string
): MedicalSpecialty | undefined {
  return MEDICAL_SPECIALTIES.find((s) => specialtySlug(s) === slug);
}

export function getTopicById(topicId: string): SpecialtyTopic | undefined {
  return ALL_SPECIALTY_TOPICS.find((t) => t.id === topicId);
}

export function getTopicsForSpecialty(
  specialty: MedicalSpecialty
): SpecialtyTopic[] {
  return (
    SPECIALTY_TOPIC_GROUPS.find((g) => g.specialty === specialty)?.topics ?? []
  );
}

export function getAllSpecialtyStaticParams(): Array<{ specialtySlug: string }> {
  return MEDICAL_SPECIALTIES.map((s) => ({ specialtySlug: specialtySlug(s) }));
}

export function getAllTopicStaticParams(): Array<{ topicId: string }> {
  return ALL_SPECIALTY_TOPICS.map((t) => ({ topicId: t.id }));
}
