export const MEDICAL_SPECIALTIES = [
  "Allergy and immunology",
  "Anaesthesiology",
  "Cardiology",
  "Cardiothoracic surgery",
  "Critical care medicine",
  "Dermatology",
  "Ear, nose, and throat",
  "Emergency medicine",
  "Endocrinology and metabolic disorders",
  "Gastroenterology and hepatology",
  "General surgery",
  "Genetics",
  "Geriatric medicine",
  "Haematology",
  "Health maintenance",
  "Hospital medicine",
  "Infectious diseases",
  "Internal medicine",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Nutrition",
  "Obstetrics and gynaecology",
  "Oncology",
  "Ophthalmology",
  "Orthopaedics",
  "Paediatrics and adolescent medicine",
  "Palliative care",
  "Primary care",
  "Psychiatry",
  "Respiratory disorders",
  "Rheumatology",
  "Sleep medicine",
  "Surgery",
  "Urology",
  "Vascular surgery",
  "Women's health",
] as const;

export type MedicalSpecialty = (typeof MEDICAL_SPECIALTIES)[number];

export type SpecialtyTopic = {
  id: string;
  title: string;
  specialty: MedicalSpecialty;
};

function topicId(specialty: string, title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  const prefix = specialty
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
  return `${prefix}-${slug}`;
}

function topicsFor(
  specialty: MedicalSpecialty,
  titles: string[]
): SpecialtyTopic[] {
  return titles.map((title) => ({
    id: topicId(specialty, title),
    title,
    specialty,
  }));
}

const ALLERGY_AND_IMMUNOLOGY_TOPICS = [
  "Acute asthma exacerbation in adults",
  "Acute rhinosinusitis",
  "Adult-onset Still's disease",
  "Allergic bronchopulmonary aspergillosis",
  "Allergic rhinitis",
  "Anaphylaxis",
  "Assessment of eosinophilia",
  "Assessment of food allergies and sensitivities",
  "Assessment of urticaria",
  "Asthma in adults",
  "Asthma in children",
  "Chronic granulomatous disease",
  "Common cutaneous drug reactions",
  "Complement deficiencies",
  "Contact dermatitis",
  "Cryoglobulinaemia",
  "Dermatitis herpetiformis",
  "Eczema",
  "Eosinophilic oesophagitis",
  "Food allergy",
  "Graft-versus-host disease",
  "Hypersensitivity pneumonitis",
  "Hypogammaglobulinaemia",
  "Insect bites and stings",
  "Mast cell activation syndrome",
  "Nasal polyps",
  "Non-allergic rhinitis",
  "Occupational asthma",
  "Paediatric acute-onset neuropsychiatric syndrome",
  "Paradoxical vocal fold motion (intermittent laryngeal obstruction)",
  "Rh incompatibility",
  "Severe combined immunodeficiency",
  "Urticaria and angio-oedema",
  "Wiskott-Aldrich syndrome",
] as const;

const ANAESTHESIOLOGY_TOPICS = [
  "Abdominal aortic aneurysm",
  "Abdominal compartment syndrome",
  "Accidental hypothermia",
  "Acute aspiration",
  "Acute asthma exacerbation in adults",
  "Acute heart failure",
  "Acute kidney injury",
  "Acute liver failure",
  "Acute pancreatitis",
  "Acute respiratory distress syndrome (ARDS)",
  "Acute respiratory failure",
  "Alcohol withdrawal",
  "Amfetamine overdose",
  "Anaphylaxis",
  "Aortic dissection",
  "Aspiration pneumonia",
  "Assessment of chest pain",
  "Assessment of cyanosis in the newborn",
  "Assessment of dyspnoea",
  "Assessment of hypercalcaemia",
  "Assessment of hyperkalaemia",
  "Assessment of hypernatraemia",
  "Assessment of hypocalcaemia",
  "Assessment of hypokalaemia",
  "Assessment of metabolic acidosis",
  "Assessment of metabolic alkalosis",
  "Assessment of nausea and vomiting, adults",
  "Assessment of respiratory acidosis",
  "Assessment of respiratory alkalosis",
  "Assessment of shock",
  "Assessment of traumatic brain injury, acute",
  "Atrial flutter",
  "Atrioventricular block",
  "Atypical pneumonia",
  "Bacterial meningitis in adults",
  "Benzodiazepine overdose",
  "Botulism",
  "Bradycardia",
  "Carbon monoxide poisoning",
  "Cardiac arrest",
  "Cardiac tamponade",
  "Central airway obstruction",
  "Chronic pain syndromes",
  "Chronic pelvic pain in women",
  "Cocaine toxicity",
  "Common toxic plant ingestions",
  "Complex regional pain syndrome",
  "Cutaneous burns",
  "Deep vein thrombosis",
  "Diabetic ketoacidosis",
  "Digoxin toxicity",
  "Discogenic low back pain",
  "Disseminated intravascular coagulation",
  "Drowning",
  "Dysbarism",
  "Electrical injury",
  "Encephalitis",
  "Epiglottitis",
  "Febrile neutropenia",
  "Foreign body aspiration",
  "Fungal meningitis",
  "Heart failure with preserved ejection fraction",
  "Heat stroke in adults",
  "Heparin-induced thrombocytopenia",
  "Hepatic encephalopathy",
  "Hepatorenal syndrome",
  "Herpes zoster infection",
  "Hospital-acquired pneumonia (non COVID-19)",
  "Hypercalcaemia of malignancy",
  "Hyperosmolar hyperglycaemic state",
  "Hypertensive emergencies",
  "Ileus",
  "Inhalation injury",
  "Ischaemic stroke",
  "Lead toxicity",
  "Malignant hyperthermia",
  "Mild traumatic brain injury",
  "Musculoskeletal lower back pain",
  "Neuroleptic malignant syndrome",
  "New-onset atrial fibrillation",
  "Non-diabetic hypoglycaemia",
  "Non-ST-elevation myocardial infarction",
  "Opioid overdose",
  "Organising pneumonia",
  "Organophosphate poisoning",
  "Overview of acid-base and electrolyte disorders",
  "Overview of dysrhythmias (cardiac)",
  "Overview of meningitis",
  "Overview of stroke",
  "Overview of substance use disorders and overdose",
  "Paracetamol overdose in adults",
  "Perioperative cardiovascular risk assessment and management for non-cardiac surgery",
  "Phaeochromocytoma",
  "Pneumocystis jirovecii pneumonia",
  "Pulmonary embolism",
  "Rhabdomyolysis",
  "Salicylate poisoning",
  "Sepsis in adults",
  "Sepsis in children",
  "Serotonin syndrome",
  "ST-elevation myocardial infarction",
  "Status epilepticus",
  "Stevens-Johnson syndrome and toxic epidermal necrolysis",
  "Subarachnoid haemorrhage",
  "Sustained ventricular tachycardias",
  "Syndrome of inappropriate antidiuretic hormone",
  "Toxic ingestions in children",
  "Toxic shock syndrome",
  "Transfusion reaction",
  "Tricyclic antidepressant overdose",
  "Unstable angina",
  "Volume depletion in adults",
  "Volume depletion in children",
] as const;

const CARDIOLOGY_TOPICS = [
  "Abdominal aortic aneurysm",
  "Acute heart failure",
  "Aortic coarctation",
  "Aortic dissection",
  "Aortic regurgitation",
  "Aortic stenosis",
  "Assessment of cardiomyopathy",
  "Assessment of chest pain",
  "Assessment of clubbing",
  "Assessment of cyanosis in the newborn",
  "Assessment of dizziness",
  "Assessment of hypertension",
  "Assessment of hypotension",
  "Assessment of mediastinal mass",
  "Assessment of palpitations",
  "Assessment of pericardial effusion",
  "Assessment of peripheral oedema",
  "Assessment of shock",
  "Assessment of syncope",
  "Assessment of tachycardia",
  "Atrial flutter",
  "Atrial myxoma",
  "Atrioventricular block",
  "Bradycardia",
  "Brugada syndrome",
  "Cardiac arrest",
  "Cardiac tamponade",
  "Carotid artery stenosis",
  "Chronic coronary disease",
  "Chronic venous insufficiency",
  "Congenital heart disease",
  "Diabetic cardiovascular disease",
  "Digoxin toxicity",
  "Essential hypertension",
  "Established atrial fibrillation",
  "Focal atrial tachycardia",
  "Gestational hypertension",
  "Heart failure with preserved ejection fraction",
  "Heart failure with reduced ejection fraction",
  "Heparin-induced thrombocytopenia",
  "Hypercholesterolaemia",
  "Hypertensive emergencies",
  "Hypertriglyceridaemia",
  "Hypertrophic cardiomyopathy",
  "Idiopathic pulmonary arterial hypertension",
  "Infective endocarditis",
  "Interatrial communications (atrial septal defects)",
  "Kawasaki disease",
  "Long QT syndrome",
  "Marfan syndrome",
  "Mitral regurgitation",
  "Mitral stenosis",
  "Myocarditis",
  "Neurally mediated reflex syncope",
  "New-onset atrial fibrillation",
  "Non-ST-elevation myocardial infarction",
  "Non-sustained ventricular tachycardias",
  "Orthostatic hypotension",
  "Overview of acute coronary syndrome",
  "Overview of dysrhythmias (cardiac)",
  "Patent ductus arteriosus",
  "Patent foramen ovale",
  "Pericarditis",
  "Perioperative cardiovascular risk assessment and management for non-cardiac surgery",
  "Peripheral arterial disease",
  "Postural orthostatic tachycardia syndrome",
  "Pulmonary regurgitation",
  "Pulmonary stenosis",
  "Raynaud's phenomenon",
  "Renal artery stenosis",
  "Rheumatic fever",
  "Shock",
  "ST-elevation myocardial infarction",
  "Superior vena cava syndrome",
  "Sustained ventricular tachycardias",
  "Takayasu's arteritis",
  "Tetralogy of Fallot",
  "Tricuspid regurgitation",
  "Tricuspid stenosis",
  "Unstable angina",
  "Ventricular septal defects",
  "Wolff-Parkinson-White syndrome",
] as const;

export const SPECIALTY_TOPIC_GROUPS: Array<{
  specialty: MedicalSpecialty;
  topics: SpecialtyTopic[];
}> = [
  {
    specialty: "Allergy and immunology",
    topics: topicsFor("Allergy and immunology", [
      ...ALLERGY_AND_IMMUNOLOGY_TOPICS,
    ]),
  },
  {
    specialty: "Anaesthesiology",
    topics: topicsFor("Anaesthesiology", [...ANAESTHESIOLOGY_TOPICS]),
  },
  {
    specialty: "Cardiology",
    topics: topicsFor("Cardiology", [...CARDIOLOGY_TOPICS]),
  },
];

export const ALL_SPECIALTY_TOPICS: SpecialtyTopic[] =
  SPECIALTY_TOPIC_GROUPS.flatMap((group) => group.topics);

export function filterSpecialtyTopics(query: string): SpecialtyTopic[] {
  const q = query.trim().toLowerCase();
  if (!q) return ALL_SPECIALTY_TOPICS;
  return ALL_SPECIALTY_TOPICS.filter(
    (topic) =>
      topic.title.toLowerCase().includes(q) ||
      topic.specialty.toLowerCase().includes(q)
  );
}

export function specialtiesWithoutTopics(): MedicalSpecialty[] {
  const withTopics = new Set(
    SPECIALTY_TOPIC_GROUPS.map((group) => group.specialty)
  );
  return MEDICAL_SPECIALTIES.filter((s) => !withTopics.has(s));
}
