export const MEDICAL_SPECIALTIES = [
  "Allergy and immunology",
  "Anaesthesiology",
  "Cardiology",
  "Cardiothoracic surgery",
  "Critical care medicine",
  "Dermatology",
  "Ear, nose, and throat",
  "Emergency medicine",
  "Endocrinology and metabolic disorders",
  "Gastroenterology and hepatology",
  "General surgery",
  "Genetics",
  "Geriatric medicine",
  "Haematology",
  "Health maintenance",
  "Hospital medicine",
  "Infectious diseases",
  "Internal medicine",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Nutrition",
  "Obstetrics and gynaecology",
  "Oncology",
  "Ophthalmology",
  "Orthopaedics",
  "Paediatrics and adolescent medicine",
  "Palliative care",
  "Primary care",
  "Psychiatry",
  "Respiratory disorders",
  "Rheumatology",
  "Sleep medicine",
  "Surgery",
  "Urology",
  "Vascular surgery",
  "Women's health",
] as const;

export type MedicalSpecialty = (typeof MEDICAL_SPECIALTIES)[number];
